apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: prometheus
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['acaa5876434cb411b84efdb70750299b-394449368.ap-northeast-2.elb.amazonaws.com:8888']       
        scheme: http