apiVersion: v1
kind: Service
metadata:
  name: hotelity-backend-ser
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  type: LoadBalancer
  selector:
    app: hotelity-backend