apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472  # Grafana runs as UID 472
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: data-grafana
          securityContext:
            runAsUser: 472  # Run as Grafana UID
            runAsGroup: 472 # Run as Grafana GID
      volumes:
        - name: data-grafana
          persistentVolumeClaim:
            claimName: data-grafana
